### ISSUE TITLE
Missing docker image

### ISSUE THREAD

**Issue by thomasrudin** [mehrdadrad/radvpn#1]
Looks like the image `radvp` is not available in the dockerhub registry:

```bash
# sudo docker run --privileged -d -p 8085:8085 -v $(pwd)/radvpn.yaml:/etc/radvpn.yaml -e RADVPN_NODE_NAME=node1 radvp
Unable to find image 'radvp:latest' locally
docker: Error response from daemon: pull access denied for radvp, repository does not exist or may require 'docker login'.
```

The `radvpn` image also does not exist (assuming a typo there) :smile:

**Comment by ratnose** [comment]
There is a dockerfile so you have to build that one to get the image.

**Comment by mehrdadrad** [comment]
you can create the image based on the dockerfile or download the image from dockerhub
docker pull mehrdadrad/radvpn:latest
I just added the dockerhub link at readme
