### ISSUE TITLE
channel passed to Notify must be buffered, else signal may be lost 

### ISSUE THREAD

**Issue by djadala** [mehrdadrad/radvpn#6]
https://github.com/mehrdadrad/radvpn/blob/b5bb965fbc1a9782e50d0f2f8724d04323ba3bd7/main.go#L41

see https://golang.org/pkg/os/signal/#Notify:

> Package signal will not block sending to c: the caller must ensure that c has sufficient buffer space  to keep up with the expected signal rate. For a channel used for notification of just one signal value, a buffer of size 1 is sufficient.

**Comment by mehrdadrad** [comment]
thanks, actually, I think the result will be identical w/o buffered channel in this case.

**Comment by djadala** [comment]
if you press ctrl-c before line 68 in main.go is reached, it will be lost.

**Comment by mehrdadrad** [comment]
i just changed it to  buffered channel
