### ISSUE TITLE
Go get fail.

### ISSUE THREAD

**Issue by cnkedao** [mehrdadrad/radvpn#8]
[root@yisu-5eaa4bd3d3d82 ~]# go get https://github.com/mehrdadrad/radvpn
package https:/github.com/mehrdadrad/radvpn: https:/github.com/mehrdadrad/radvpn: invalid import path: malformed import path "https:/github.com/mehrdadrad/radvpn": invalid char ':'
[root@yisu-5eaa4bd3d3d82 ~]# go version
go version go1.13.6 linux/amd64

**Comment by mehrdadrad** [comment]
pls try the below. i just fixed the readme.
go get github.com/mehrdadrad/radvpn
